# Generated by Django 3.2.9 on 2023-02-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankPortal', '0002_auto_20230202_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_portal_new',
            name='count',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
