# Generated by Django 3.2.9 on 2023-02-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankPortal', '0004_auto_20230207_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_portal_new',
            name='view_count',
        ),
        migrations.AddField(
            model_name='bank_portal_new',
            name='count_view',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bank_portal_new',
            name='count',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]

