# Generated by Django 3.2.9 on 2023-02-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankPortal', '0006_auto_20230207_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_portal_new',
            name='count_view',
        ),
    ]
