# Generated by Django 3.2.9 on 2023-02-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankPortal', '0008_auto_20230207_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_portal_new',
            name='viewed_applications',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='bank_portal_new',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank_portal_new',
            name='count_view',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
