# Generated by Django 3.2.9 on 2023-02-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankPortal', '0009_auto_20230208_0726'),
    ]

    operations = [

    ]
