# Generated by Django 3.2.9 on 2023-02-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankPortal', '0010_delete_bank'),
    ]

    operations = [

    ]
