# Generated by Django 3.2.9 on 2022-11-28 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('contact_person', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('regions', models.CharField(max_length=200, null=True)),
                ('years', models.IntegerField()),
                ('number_of_stuff', models.CharField(max_length=200, null=True)),
                ('avg_salary', models.CharField(max_length=200, null=True)),
                ('req_service', models.CharField(max_length=200, null=True)),
                ('sector', models.CharField(max_length=200, null=True)),
                ('saudi_stuff', models.CharField(max_length=200, null=True)),
                ('legal_form', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
