# Generated by Django 3.2.9 on 2022-11-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='business_cap',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='number_of_branches',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='years',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
