# Generated by Django 3.2.9 on 2022-12-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_employee_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
