# Generated by Django 3.2.9 on 2022-12-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_employee_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='permission',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
