# Generated by Django 3.2.9 on 2023-02-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
