# Generated by Django 3.2.9 on 2023-02-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_employee_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='count_paid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='count_viewed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
